imports:
  Merchant: Domain.Types.Merchant
  MerchantOperatingCity: Domain.Types.MerchantOperatingCity
  BaseUrl: Servant.Client.Core
  showBaseUrl: Kernel.Prelude
  parseBaseUrl: Kernel.Prelude
  VehicleCategory: BecknV2.OnDemand.Enums

BecknConfig:
  tableName: beckn_config

  fields:
    id: Id BecknConfig
    domain: Text
    subscriberId: Text
    subscriberUrl: BaseUrl
    gatewayUrl: BaseUrl
    registryUrl: BaseUrl
    uniqueKeyId: Text
    settlementType: Maybe Text
    paymentParamsJson: Maybe Text
    vehicleCategory: VehicleCategory|NoRelation
    collectedBy: PaymentCollectedBy
    staticTermsUrl: Maybe BaseUrl
    buyerFinderFee: Maybe Text # becomes redundant
    settlementWindow: Maybe Text
    searchTTLSec: Maybe Int
    selectTTLSec: Maybe Int
    initTTLSec: Maybe Int
    confirmTTLSec: Maybe Int
    confirmBufferTTLSec: Maybe Int
    bapIFSC: Maybe Text
    statusTTLSec: Maybe Int
    trackTTLSec: Maybe Int
    ratingTTLSec: Maybe Int
    cancelTTLSec: Maybe Int
    # blackListedVehicleCategories: -- shrey00 : type complete karo

  types:
    VehicleCategory:
      enum: "CAB, AUTO_RICKSHAW, METRO, MOTORCYCLE, AMBULANCE, TWO_WHEELER"

    PaymentCollectedBy:
      enum: "BAP, BPP"

  default:
    vehicleCategory: "'CAB'"
    collectedBy: "'BPP'"

  queries:
    findByMerchantIdDomainAndVehicle:
      kvFunction: findOneWithKV
      where:
        and: [merchantId, domain, vehicleCategory]
    findByMerchantIdAndDomain:
      kvFunction: findAllWithKV
      where:
        and: [merchantId, domain]
    findById:
      kvFunction: findOneWithKV
      where: id
    findByMerchantIdDomainandMerchantOperatingCityId:
      kvFunction: findOneWithKV
      where:
        and: [merchantId, domain, merchantOperatingCityId]

  beamType:
    subscriberUrl: Text
    gatewayUrl: Text
    registryUrl: Text
    staticTermsUrl: Maybe Text

  toTType:
    subscriberUrl: showBaseUrl|I
    gatewayUrl: showBaseUrl|I
    registryUrl: showBaseUrl|I
    staticTermsUrl: (Kernel.Prelude.fmap showBaseUrl)|I

  fromTType:
    subscriberUrl: parseBaseUrl|MI
    gatewayUrl: parseBaseUrl|IM
    registryUrl: parseBaseUrl|MI
    staticTermsUrl: (Kernel.Prelude.maybe (return Kernel.Prelude.Nothing) (Kernel.Prelude.fmap Kernel.Prelude.Just . parseBaseUrl))|MI
