imports:
  Merchant: Domain.Types.Merchant
  MerchantOperatingCity: Domain.Types.MerchantOperatingCity
  EmailOTPConfig: Email.Types
  KaptureConfig: IssueManagement.Common
  ExotelMapping: Domain.Types.Extra.RiderConfig
  Value: Data.Aeson
  NominalDiffTime: Kernel.Prelude
  Seconds: Kernel.Types.Common
  CxAgentDetails: IssueManagement.Common

RiderConfig:
  tableName: rider_config

  derives: "Show, Generic, ToJSON, FromJSON"

  fields:
    merchantOperatingCityId: Id MerchantOperatingCity
    enableLocalPoliceSupport: Bool
    localPoliceNumber: Maybe Text
    enableSupportForSafety: Bool
    videoFileSizeUpperLimit: Int
    timeDiffFromUtc: Seconds
    enableEmergencyContactAddedMessage: Bool
    safetyCheckStartTime: Seconds
    safetyCheckEndTime: Seconds
    trackingShortUrlPattern: Text
    specialZoneRadius: Int
    appUrl: Text
    collectAutoCompleteData: Maybe Bool
    distanceWeightage: Int
    collectMMIRouteData: Maybe Bool
    isAvoidToll: Bool
    autoUnblockSafetyCenterAfterDays: Int
    placeNameCacheExpiryDays: Maybe Int
    bookingSyncStatusCallSecondsDiffThreshold: Maybe Int
    kaptureQueue: Text # deprecated
    kaptureConfig: IssueManagement.Common.KaptureConfig
    emailOtpConfig: Maybe Email.Types.EmailOTPConfig
    ivrTriggerDelay: NominalDiffTime
    executePaymentDelay: NominalDiffTime
    cancellationPaymentDelay: NominalDiffTime
    policeTriggerDelay: NominalDiffTime
    exotelAppIdMapping: Maybe ExotelMapping
    hardLimitForSafetyJobs: Int
    exotelStatusCheckSchedulerDelay : Int
    incidentReportSupport: Bool
    settleCancellationFeeBeforeNextRide: Maybe Bool
    cxAgentDetails: "Maybe [CxAgentDetails]"
    csAlertTriggerDelay: NominalDiffTime
    avgSpeedInKmPerHr: Kilometers
    sensitiveWords: "Maybe [Text]"
    sensitiveWordsForExactMatch : "Maybe [Text]"
    payoutBatchSize: Maybe Int
    payoutBatchDelay: NominalDiffTime
    makeMultiModalSearch: Bool
    maximumWalkDistance: Meters
    driverReferredSearchReqExpiry: Maybe Seconds

  beamType:
    ivrTriggerDelay: Maybe Seconds
    policeTriggerDelay: Maybe Seconds
    hardLimitForSafetyJobs: Maybe Seconds
    exotelStatusCheckSchedulerDelay : Maybe Seconds
    incidentReportSupport: Maybe Bool
    csAlertTriggerDelay: Maybe Seconds
    avgSpeedInKmPerHr: Maybe Kilometers
    payoutBatchDelay: Maybe Seconds
    executePaymentDelay: Maybe Seconds
    cancellationPaymentDelay: Maybe Seconds
    makeMultiModalSearch: Maybe Bool
    maximumWalkDistance: Maybe Meters

  constraints:
    merchantOperatingCityId: PrimaryKey

  fromTType:
    ivrTriggerDelay: fromMaybe 3000 (Kernel.Utils.Common.secondsToNominalDiffTime <$> ivrTriggerDelay)|E
    executePaymentDelay: fromMaybe 60 (Kernel.Utils.Common.secondsToNominalDiffTime <$> executePaymentDelay)|E
    cancellationPaymentDelay: fromMaybe 60 (Kernel.Utils.Common.secondsToNominalDiffTime <$> cancellationPaymentDelay)|E
    policeTriggerDelay: fromMaybe 60 (Kernel.Utils.Common.secondsToNominalDiffTime <$> policeTriggerDelay)|E
    hardLimitForSafetyJobs: fromMaybe 21600 ((.getSeconds) <$> hardLimitForSafetyJobs)|E
    exotelStatusCheckSchedulerDelay: maybe 120 (.getSeconds) exotelStatusCheckSchedulerDelay|E
    incidentReportSupport: fromMaybe False incidentReportSupport|E
    csAlertTriggerDelay: fromMaybe 60 (Kernel.Utils.Common.secondsToNominalDiffTime <$> csAlertTriggerDelay)|E
    avgSpeedInKmPerHr: fromMaybe 20 avgSpeedInKmPerHr|E
    payoutBatchDelay: fromMaybe 10 (Kernel.Utils.Common.secondsToNominalDiffTime <$> payoutBatchDelay)|E
    makeMultiModalSearch: fromMaybe False makeMultiModalSearch|E
    maximumWalkDistance: fromMaybe (600) maximumWalkDistance|E

  toTType:
    ivrTriggerDelay: (Just . Kernel.Utils.Common.nominalDiffTimeToSeconds)|I
    executePaymentDelay: (Just . Kernel.Utils.Common.nominalDiffTimeToSeconds)|I
    cancellationPaymentDelay: (Just . Kernel.Utils.Common.nominalDiffTimeToSeconds)|I
    policeTriggerDelay: (Just . Kernel.Utils.Common.nominalDiffTimeToSeconds)|I
    hardLimitForSafetyJobs: Just $ Kernel.Types.Common.Seconds hardLimitForSafetyJobs|E
    exotelStatusCheckSchedulerDelay: Just $ Kernel.Types.Common.Seconds exotelStatusCheckSchedulerDelay|E
    incidentReportSupport: Just incidentReportSupport|E
    csAlertTriggerDelay: (Just . Kernel.Utils.Common.nominalDiffTimeToSeconds)|I
    avgSpeedInKmPerHr: Just avgSpeedInKmPerHr|E
    payoutBatchDelay: (Just . Kernel.Utils.Common.nominalDiffTimeToSeconds)|I
    makeMultiModalSearch: Just makeMultiModalSearch|E
    maximumWalkDistance: Just maximumWalkDistance|E

  default:
    enableLocalPoliceSupport: "false"
    enableSupportForSafety: "false"
    videoFileSizeUpperLimit: "15000000"
    enableEmergencyContactAddedMessage: "true"
    appUrl: "'nammayatri.in/link/rider/rmxw'"
    timeDiffFromUtc: "19800"
    safetyCheckStartTime: "75600"
    safetyCheckEndTime: "21600"
    trackingShortUrlPattern: "'nammayatri.in/t/'"
    specialZoneRadius: "150"
    distanceWeightage: "70"
    isAvoidToll: "true"
    autoUnblockSafetyCenterAfterDays: "14"
    kaptureQueue: "''"
    kaptureConfig: "'{\"kaptureQueue\":\"\", \"disposition\":\"\"}'"
    exotelStatusCheckSchedulerDelay: "120"
    avgSpeedInKmPerHr: "20"
    makeMultiModalSearch: "false"
    maximumWalkDistance: "600"

  queries:
    findByMerchantOperatingCityId:
      kvFunction: findOneWithKV
      where: merchantOperatingCityId

    findExotelAppletMappingByMOCID:
      kvFunction: findOneWithKV
      where: merchantOperatingCityId

  sqlType:
    emailOtpConfig: "json"
    kaptureConfig: "json"
    exotelAppIdMapping: "json"
    cxAgentDetails: text []
    sensitiveWords: text []
    sensitiveWordsForExactMatch: text []

  extraOperations:
    - EXTRA_DOMAIN_TYPE_FILE
