# App repository - https://github.com/beckn-dev/yatri_customer_support/ (private repo)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beckn-app-customer-support-$DEPLOY_VARIANT
  namespace: atlas
  labels:
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beckn-app-customer-support-$DEPLOY_VARIANT
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: beckn-app-customer-support-$DEPLOY_VARIANT
        version: latest
    spec:
      containers:
        - env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: asia.gcr.io/jp-dev-chaos/beckn-customer-support-dashboard:$BUILD_VERSION
          name: beckn-app-customer-support-$DEPLOY_VARIANT
          ports:
            - containerPort: 3000
              name: app-http
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 3Gi
          securityContext:
            privileged: false
      dnsConfig:
        options:
          - name: ndots
            value: "1"
          - name: single-request-reopen
      imagePullSecrets:
        - name: gpay-gcr
      terminationGracePeriodSeconds: 90
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: atlas
  name: beckn-app-customer-support-$DEPLOY_VARIANT
  labels:
    app: beckn-app-customer-support-$DEPLOY_VARIANT
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: app-http
  selector:
    app: beckn-app-customer-support-$DEPLOY_VARIANT
