name:                beckn-epass
version:             0.1.0.0
github:              "juspay/beckn-epass"
license:             BSD3
author:              "Aravind Gopal Mallapureddy"
maintainer:          "aravind.mallapureddy@juspay.in"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://bitbucket.org/juspay/beckn-epass#readme>

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - BlockArguments

dependencies:
- aeson
- aeson-pretty
- base >= 4.7 && < 5
- beam-core
- beam-mysql
- bytestring
- containers
- cryptonite
- data-default
- euler-hs
- http-api-data
- http-client
- http-types
- lens
- pureMD5
- purescript-bridge
- servant
- servant-client
- servant-multipart
- servant-purescript
- servant-server
- servant-subscriber
- servant-swagger
- swagger2
- text
- vault
- wai
- wai-extra
- warp
- time
- template-haskell

library:
  source-dirs: src

executables:
  beckn-epass-exe:
    main:                Main.hs
    source-dirs:         app/beckn-epass
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beckn-epass
  beckn-gateway-exe:
    main:                Main.hs
    source-dirs:         app/beckn-gateway
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beckn-epass

tests:
  beckn-epass-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beckn-epass
    - hspec
    - hspec-core
    - hspec-wai
    - http-client-tls
    - servant-client
