version: "3"
services:
  app-db:
    image: "postgis/postgis:12-3.0"
    container_name: "atlas-app"
    ports:
      - "5433:5432"
    volumes:
      - ./sql-seed/app-backend-seed.sql:/docker-entrypoint-initdb.d/1-app-backend-seed.sql:Z
      - ./local-testing-data/app-backend.sql:/docker-entrypoint-initdb.d/2-app-backend-testing-data.sql:Z
    environment:
      - POSTGRES_DB=atlas_app
      - POSTGRES_USER=atlas
      - POSTGRES_PASSWORD=atlas
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256
  transporter-db:
    image: "postgis/postgis:12-3.0"
    container_name: "atlas-transporter"
    ports:
      - "5434:5432"
    volumes:
      - ./sql-seed/transporter-backend-seed.sql:/docker-entrypoint-initdb.d/1-transporter-backend-seed.sql:Z
      - ./local-testing-data/beckn-transport.sql:/docker-entrypoint-initdb.d/2-beckn-transport-testing-data.sql:Z
    environment:
      - POSTGRES_DB=atlas_transporter
      - POSTGRES_USER=atlas
      - POSTGRES_PASSWORD=atlas
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256
  gateway-db:
    image: "postgis/postgis:12-3.0"
    container_name: "atlas-gateway"
    ports:
      - "5435:5432"
    volumes:
      - ./sql-seed/gateway-backend-seed.sql:/docker-entrypoint-initdb.d/1-gateway-backend-seed.sql:Z
      - ./local-testing-data/gateway.sql:/docker-entrypoint-initdb.d/2-gateway-testing-data.sql:Z
    environment:
      - POSTGRES_DB=atlas_gateway
      - POSTGRES_USER=atlas
      - POSTGRES_PASSWORD=atlas
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256
  fmd-wrapper-db:
    image: "postgis/postgis:12-3.0"
    container_name: "atlas-fmd-wrapper"
    ports:
      - "5436:5432"
    volumes:
      - ./sql-seed/fmd-wrapper-backend-seed.sql:/docker-entrypoint-initdb.d/1-fmd-wrapper-backend-seed.sql:Z
      - ./local-testing-data/fmd-wrapper.sql:/docker-entrypoint-initdb.d/2-fmd-wrapper-testing-data.sql:Z
    environment:
      - POSTGRES_DB=atlas_fmd_wrapper
      - POSTGRES_USER=atlas
      - POSTGRES_PASSWORD=atlas
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256
  transporter-redis:
    image: "redis:5"
    ports:
      - "6379:6379"
  passetto-db:
    image: "postgres:12.3"
    container_name: "passetto-enc-db"
    ports:
      - "5422:5432"
    volumes:
      - ./sql-seed/passetto-seed.sql:/docker-entrypoint-initdb.d/create_schema.sql:Z
    environment:
      - POSTGRES_DB=passetto
      - POSTGRES_USER=passetto
      - POSTGRES_PASSWORD=passetto
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256
  passetto-server:
    image: "juspayin/passetto-hs:0b18530"
    container_name: "passetto-enc-server"
    command: demo # for DEV only
    ports:
      - "8021:8012"
    environment:
      - "PASSETTO_PG_BACKEND_CONN_STRING=postgresql://passetto:passetto@passetto-enc-db:5432/passetto"
