version: "3"
services:
  app-db:
    image: "postgres:12.3"
    container_name: "atlas-app"
    ports:
      - "5433:5432"
    volumes:
      - ./sql-seed/app-backend-seed.sql:/docker-entrypoint-initdb.d/app-backend-seed.sql:Z
    environment:
      - POSTGRES_DB=atlas_app
      - POSTGRES_USER=atlas
      - POSTGRES_PASSWORD=atlas
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256
  transporter-db:
    image: "postgres:12.3"
    container_name: "atlas-transporter"
    ports:
      - "5434:5432"
    volumes:
      - ./sql-seed/transporter-backend-seed.sql:/docker-entrypoint-initdb.d/transporter-backend-seed.sql:Z
    environment:
      - POSTGRES_DB=atlas_transporter
      - POSTGRES_USER=atlas
      - POSTGRES_PASSWORD=atlas
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256
  transporter-redis:
    image: "redis:5"
    ports:
      - "6379:6379"
  encryption-server:
    image: "juspayin/passetto-hs:9c62b19"
    container_name: "encryption-server"
    command: demo  # for DEV only
    ports:
      - "8021:8012"
    environment:
      - "PASSETTO_PG_BACKEND_CONN_STRING=postgresql://passetto:passetto@encryption-keystorage:5432/passetto"
  encryption-keystorage:
    image: "postgres:11.7"
    container_name: "encryption-keystorage"
    ports:
      - "5422:5432"
    volumes:
      - passetto-enc-volume:/var/lib/postgresql/data
      - ./passetto/seed.sql:/docker-entrypoint-initdb.d/create_schema.sql:Z
    environment:
      - POSTGRES_DB=passetto
      - POSTGRES_USER=passetto
      - POSTGRES_PASSWORD=passetto

volumes:
  passetto-enc-volume:
