name: app-backend
version: 0.1.0.0
github: "juspay/beckn"
license: AllRightsReserved
author: "Juspay"
maintainer: "Juspay"
copyright: "2020 Juspay Technologies Private Limited"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://bitbucket.org/juspay/beckn#readme>

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - BlockArguments

dependencies:
  - aeson
  - aeson-pretty
  - base >= 4.7 && < 5
  - base64-bytestring
  - beam-core
  - beam-postgres
  - bytestring
  - containers
  - cryptonite
  - data-default
  - euler-hs
  - http-api-data
  - http-client
  - http-types
  - lens
  - mtl
  - prometheus-client
  - wai-middleware-prometheus
  - prometheus-metrics-ghc
  - postgresql-simple
  - pureMD5
  - purescript-bridge
  - servant
  - servant-client
  - servant-multipart
  - servant-purescript
  - servant-server
  - servant-subscriber
  - servant-swagger
  - swagger2
  - text
  - vault
  - wai
  - wai-extra
  - warp
  - time
  - template-haskell
  - random-strings

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -fhide-source-paths
    - -Werror=unused-imports
    - -Werror=missing-fields
  dependencies:
    - beckn-core

executables:
  app-backend-exe:
    main: Main.hs
    source-dirs: server
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N -T"'
    dependencies:
      - app-backend
      - beckn-core
