name: beckn-transport
version: 0.1.0.0
github: "juspay/beckn"
license: AllRightsReserved
author: "Juspay"
maintainer: "Juspay"
copyright: "2020 Juspay Technologies Private Limited"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://bitbucket.org/juspay/beckn#readme>

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - BlockArguments

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - generic-lens
  - beam-core
  - beam-postgres
  - bytestring
  - cryptonite
  - containers
  - euler-hs
  - http-api-data
  - http-client
  - http-types
  - mtl
  - servant
  - servant-client
  - servant-client-core
  - servant-server
  - swagger2
  - text
  - wai
  - wai-extra
  - warp
  - time
  - unix
  - stm
  - random-strings
  - tasty
  - tasty-hunit
  - postgresql-simple
  - resource-pool

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -fhide-source-paths
    - -Werror
  dependencies:
    - beckn-core

executables:
  beckn-transport-exe:
    main: Main.hs
    source-dirs: server
    other-modules: []
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N -T"'
    dependencies:
      - beckn-transport
      - beckn-core
  beckn-transport-btm-exe:
    main: BackgroundTaskManagerMain.hs
    source-dirs: server
    other-modules: []
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N -T"'
    dependencies:
      - beckn-transport
      - beckn-core

tests:
  beckn-transport-tests:
    main: Main.hs
    source-dirs:
      - test/app
      - test/src
    dependencies:
      - tasty
      - tasty-hunit
      - beckn-transport
      - beckn-core
