imports:
  Merchant: Domain.Types.Merchant
  BaseUrl: Servant.Client.Core
  showBaseUrl: Kernel.Prelude
  parseBaseUrl: Kernel.Prelude

BecknConfig:
  tableName: beckn_config

  fields:
    id: Id BecknConfig
    domain: Text
    registryUrl: BaseUrl

  excludedFields: [merchantOperatingCityId]

  queries:
    findByMerchantIdAndDomain:
      kvFunction: findOneWithKV
      where:
        and: [merchantId, domain]
    findById:
      kvFunction: findOneWithKV
      where: id

  beamType:
    registryUrl: Text

  toTType:
    registryUrl: showBaseUrl|I

  fromTType:
    registryUrl: parseBaseUrl|MI
