imports:
  TimeBound: Kernel.Types.TimeBound
  Merchant: Domain.Types.Merchant
  MerchantOperatingCity: Domain.Types.MerchantOperatingCity
  LogicDomain: Lib.Yudhishthira.Types

TimeBoundConfig:
  tableName: time_bound_config

  fields:
    merchantOperatingCityId: Id MerchantOperatingCity
    timeBoundDomain: LogicDomain
    name: Text
    timeBounds: TimeBound|NoRelation

  constraints:
    name: PrimaryKey
    merchantOperatingCityId: PrimaryKey
    timeBoundDomain: PrimaryKey

  queries:
    findByCityAndDomain:
      kvFunction: findAllWithKV
      where:
        and: [merchantOperatingCityId, timeBoundDomain]

  cachedQueries:
    findByPrimaryKey:
      keyParams: [merchantOperatingCityId, name, timeBoundDomain]
      dbQuery: findByPrimaryKey
      dbQueryParams: [merchantOperatingCityId, name, timeBoundDomain]
      queryType: FindAndCache
    findByCityAndDomain:
      withCrossAppRedis: true
      returnType: Array
      keyParams: [merchantOperatingCityId, timeBoundDomain]
      dbQuery: findByCityAndDomain
      dbQueryParams: [merchantOperatingCityId, timeBoundDomain]
      queryType: FindAndCache

  extraOperations:
    - EXTRA_QUERY_FILE
    - EXTRA_CACHED_QUERY_FILE

  excludedFields: [merchantId]